# Site settings
title: Neolux Plaza
description: 
cover: assets/images/radhakrishna.jpg
logo: assets/images/logo.jpg
favicon: assets/images/favicon.jpg
baseurl: "/blog/" # the subpath of your site, e.g. /blog/ or / for root
url: "http://plaza.neolux.ml" # the base hostname & protocol for your site

pagination:

  # Site-wide kill switch, disabled here it doesn't run at all 
  enabled: true

  # Set to 'true' to enable pagination debugging. This can be enabled in the site config or only for individual pagination pages
  debug: false

  per_page: 5

# Social
bilibili: bilibili
twitter: twitter
github:  github

#Additional Pages
about: about
contact: contact
privacy-policy: privacy-policy


permalink: /:title


# Google Analytics
analytics_id: ""

# Build settings
markdown: kramdown

kramdown:
  parse_block_html: true

plugins:
  - jekyll-paginate-v2


# Settings for rake task
safe: False
lsi: False
username: peak-neo #github username
repo: peak-neo.github.io #github repository
branch: master #branch
relative_source: ../hanuman/ #source directory
destination: ../hanuman-pages/ #destination directory
production_url:  http://plaza.neolux.ml
source_url:  https://github.com/peak-neo/peak-neo.github.io #source repository url

exclude:
  - README.md
  - Rakefile
  - Gemfile
  - Gemfile.lock
  - changelog.md
  - "*.Rmd"
  - vendor
  - .travis.yml